---
# handlers file for jenkins
- name: Reloading Jenkins service
  systemd:
    name: jenkins
    daemon-reload: yes
    state: restarted
    enabled: yes
  become: yes
  listen: "Reload service"

- name: Wait for starting Jenkins
  wait_for:
    port: "{{app_port}}"
    host: "{{ansible_host}}"
    delay: 5
  listen: "check state"