---
# tasks file for java
- name: Installing java
  yum: "name={{ item }} state=present"
  with_items: "{{ java_packages }}"
  become: yes

- name: Get Java Version
  shell: java -version |& awk -F '"' '/version/ {print $2}'
  register: java_version
  changed_when: no
- debug: msg="{{ java_version.stdout_lines }}"