---
# tasks file for jenkins
- name: Creating jenkins user group
  group:
    name: "{{ jenkins_group }}"
  become: yes

- name: Creating user for jenkins service
  user:
    name: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
  become: yes


- name: Creating jenkins home directory
  file:
    path: "{{ jenkins_home }}"
    state: directory
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
  become: yes

- name: Download jenkins
  get_url:
    url: "{{ jenkins_war_url }}{{ jenkins_version }}/jenkins.war"
    dest: "{{ jenkins_home }}jenkins.war"
  become: yes

- name: Creating jenkins service
  template:
    src: jenkins.service.j2
    dest: /etc/systemd/system/jenkins.service
    owner: root
    group: root
    mode: 0644
  become: yes
  notify: Reload service

- name: Starting jenkins service
  systemd:
    name: jenkins
    state: started
    enabled: yes
  become: yes

- name: Waiting for jenkins to boot
  wait_for:
    port: 8080
    delay: 50

- name: Checking jenkins
  shell: |
    systemctl is-active jenkins
  register: jenkins_status
  changed_when: no
- debug: msg="{{ jenkins_status.stdout_lines}}"

- name: Getting jenkins init password
  shell: cat {{ jenkins_home }}secrets/initialAdminPassword
  changed_when: no
  become: yes
  register: init_password
- debug: msg="Initial jenkins password {{init_password.stdout}}"

- name: Creating fact folder
  become: yes
  file:
    path: /etc/ansible/facts.d
    state: directory

- name: Saving password fact
  become: yes
  copy:
    content:
      {
        "initial_password": "{{ init_password.stdout }}"
      }
    dest: /etc/ansible/facts.d/jenkins_password.fact

- name: Saving jenkins status fact
  become: yes
  copy:
    content:
      {
        "status": "{{ jenkins_status.stdout_lines }}"
      }
    dest: /etc/ansible/facts.d/jenkins_status.fact
