---
# tasks file for httpd

- name: ensuring httpd exists and latest version
  remote_user: devops
  yum:
    name: httpd
    state: latest
  become: yes

- name: configuring httpd
  template:
    src: templates/vhost.conf.j2
    dest: /etc/httpd/conf.d/jenkins.conf
  become: yes
  notify:
    - restart httpd

- name: enabling httpd service
  systemd:
    name: httpd
    state: started
    enabled: yes
  become: yes

- name: checking installation results
  shell: |
    httpd -version
    systemctl is-active httpd
  register: httpd_status

- debug: msg="{{ httpd_status.stdout_lines }}"